name: Workflow2

on:
  push:
    branches:
      - main

jobs:
  clone-and-process:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone temporary repository
        run: git clone https://github.com/ptmnational/temp_repo.git temp_repo
        
      - name: Checkout branch
        run: |
          cd temp_repo
          git checkout temp_branch

      - name: Unzip files
        run: unzip -o my_files.zip

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
       
          git add .
          git commit -m "Unzipped files from work1"
          git push https://x-access-token:${{ secrets.WK2_TOKEN }}@github.com/ptmnational/work2.git HEAD:refs/heads/main
          
      # Ajoutez ici les étapes pour extraire le contenu du fichier ZIP,
      # faire un commit et supprimer le fichier ZIP.
