name: Workflow2

on:
  push:
    branches:
      - main

jobs:
  download-unzip-commit-and-remove:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2



          
      - name: Clone work1
        run: |
          git clone https://github.com/ptmnational/work1 ./repo1
          cd ./repo1
          
      - name: Download ZIP from work1
        run: |
          curl -o my_files.zip https://raw.githubusercontent.com/ptmnational/work1/main/my_files.zip
          
      - name: Unzip files
        run: unzip -o my_files.zip

      - name: Remove ZIP file
        run: rm my_files.zip
        
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
       
          git add .
          git commit -m "Unzipped files from work1"
          git push https://x-access-token:${{ secrets.WK2_TOKEN }}@github.com/ptmnational/work2.git HEAD:refs/heads/main
        
