name: Workflow2

on:
  push:
    branches:
      - main

jobs:
  download-unzip-commit-and-remove:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Clone repos1
        run: |
          git clone https://github.com/<owner>/<repo1-name> ./repo1
          cd ./repo1
          
      - name: Download ZIP from repos1
        run: |
          curl -o my_files.zip https://raw.githubusercontent.com/ptmnational/work1/main/my_files.zip
          
      - name: Unzip files
        run: unzip my_files.zip
        
      - name: Commit changes
        run: |
          git add .
          git commit -m "Unzipped files from repos1"
          git push origin main
        
      - name: Remove ZIP file
        run: rm my_files.zip
