name: Workflow2.1

on:
  workflow_run:
    workflows: ["Workflow1"]
    types:
      - completed

jobs:
  download-zip-and-process:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Download ZIP from repository1
        run: |
          curl -LJO https://raw.githubusercontent.com/ptmnational/work1/main/my_files.zip
      
      
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      
      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Add extracted files"
          git push https://ptmnational:$TOKEN@github.com/ptmnational/work2.git HEAD:main
        env:
          TOKEN: ${{ secrets.ACC_TOKEN }}  
